version: '2'

services:
  web:
    build: django_weather_reminder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_weather_reminder/:/usr/src/django_weather_reminder/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbit
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_weather_reminder

  redis:
      restart: unless-stopped
      image: redis:7.0.5-alpine
      expose:
          - 6379

  rabbit:
      hostname: rabbit
      image: rabbitmq:3.6.9
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      ports:
          - "5672:5672"
          - "15672:15672"

  worker:
    build: ./django_weather_reminder
    command: celery -A django_weather_reminder worker -l INFO
    volumes:
      - .:/code:Z
    env_file:
      - ./.env
    links:
        - db
        - rabbit
        - redis
    depends_on:
        - rabbit
    # Celery worker
  beat:
    build: ./django_weather_reminder
    command: celery -A django_weather_reminder beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code:Z
    env_file:
      - ./.env
    links:
        - worker
        - db
        - redis
    depends_on:
        - worker
        - rabbit
        - redis
volumes:
  postgres_data: